trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'acraetest'
  imageName: 'hello-world50'
  tag: 'v1'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'ADO-dockerimage'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az acr login --name acraetest
      docker build -t acraetest.azurecr.io/hello-world50:v1 .
      docker push acraetest.azurecr.io/hello-world50:v1 
