trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'acraetest'
  imageName: 'hello-world5'
  tag: 'v1'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'acr-image-sit'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript:
      az acr login --name acraetest
      docker build -t acraetest.azurecr.io/hello-world:v1 .
      docker push acraetest.azurecr.io/hello-world:v1 
