trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'acraesit'
  imageName: 'hello-world2'
  tag: 'v1'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'acr-image-sit'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az acr login --name acraesit
      docker build -t acraesit.azurecr.io/hello-world:v1 .
      docker push acraesit.azurecr.io/hello-world:v1 
